### PR TITLE
Trying to fix a file not found error.

### PR DESCRIPTION
**Pull request by michelescarlato**
Hi @amphioxis ,

This should fix the file not found error for the requirements.txt pypi resolved.

It should be widely tested, but to me seemed fine when I tried it.

Also @gdrosos Giorgos agreed upon this approach.

PS the main file doesn't need to be merged.

### CODE REVIEW

**Comment by amphioxis** [comment]
This doesn't work:
The `if` statement just checks if the file is there or not. In case the file is not generated, what do you want to do?
If the file is not there, the module just returns `NoneType` and therefore, the whole process fails with
`TypeError: expected str, bytes or os.PathLike object, not NoneType`.

The question you answer with this fix is: Is the file there?
The question you need to answer is: Why is the file not created?

**Comment by michelescarlato** [comment]
@gdrosos , what is your opinion here?

**Comment by amphioxis** [comment]
I think the problem lays deeper and this new solution just creates an endless loop as the file is not being created.
I opened an Issue #32

**Comment by gdrosos** [comment]
I 

> @gdrosos , what is your opinion here?
> 
> Maybe something like this could fix it:
> 
> https://github.com/fasten-project/fasten-pypi-plugin/blob/7b63e9f7f8c7c04c0ce01d13bd36bbcb88e853aa/src/fasten/executePypiResolver.py#L27-L29

I you aim to fix the fileNotFoundError when the file is not present, then  I think this PR fixes this issue.
But if the resolver cannot reoslve the dependencies it would result in an endless loop

**Pull request closed without merging**
